apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongodb
  name: mongo-nodeport-svc
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  selector:
    matchLabels:
      name: mongo
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo:latest
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
